extends:
  - "@commitlint/config-conventional"
rules:
  type-enum:
    - 2
    - always
    - - build
      - ci
      - docs
      - enhance
      - feat
      - fix
      - perf
      - refactor
      - remodel
      - revert
      - style
      - test
      - vcs
